import type { AIProvider } from '../integrations/ai/provider.interface.js'
import type { ErrorMonitoringProvider } from '../integrations/error-monitoring/provider.interface.js'
import type { NotificationProvider } from '../integrations/notification/provider.interface.js'
import { GitHubClient, type GitHubClientConfig } from '../integrations/github/client.js'
import type { EngineResult } from '../types/result.js'

// ─────────────────────────────────────────
// 엔진 설정
// ─────────────────────────────────────────

export interface EngineConfig {
  ai: AIProvider
  errorMonitoring: ErrorMonitoringProvider
  notification?: NotificationProvider
  github: GitHubClientConfig
}

// ─────────────────────────────────────────
// 엔진 본체
// ─────────────────────────────────────────

export class KintsugiEngine {
  private ai: AIProvider
  private errorMonitoring: ErrorMonitoringProvider
  private notification?: NotificationProvider
  private github: GitHubClient

  constructor(config: EngineConfig) {
    this.ai = config.ai
    this.errorMonitoring = config.errorMonitoring
    this.notification = config.notification
    this.github = new GitHubClient(config.github)
  }

  async run(rawPayload: unknown): Promise<EngineResult> {
    try {
      // 1. 에러 파싱
      const error = this.errorMonitoring.parse(rawPayload)

      // 2. 레포 파일 트리 가져오기
      const fileTree = await this.github.getFileTree()

      // 3. AI 1차: 어떤 파일을 봐야 하는지 판단
      const filePaths = await this.ai.analyzeError(error, fileTree)

      if (filePaths.length === 0) {
        return { success: false, error: 'AI could not determine which files to examine' }
      }

      // 4. 해당 파일들 소스코드 읽기
      const sourceFiles = await this.github.getFileContents(filePaths)

      // 5. AI 2차: 수정안 생성
      const fix = await this.ai.generateFix(error, sourceFiles)

      if (fix.changes.length === 0) {
        return { success: false, error: 'AI could not generate a fix' }
      }

      // 6. 브랜치 생성 → 파일 수정 → PR 생성
      const branchName = `kintsugi/fix-${error.id}`

      await this.github.createBranch(branchName)

      for (const change of fix.changes) {
        const original = sourceFiles.find((f) => f.path === change.path)
        if (!original) continue

        await this.github.updateFile(
          branchName,
          change.path,
          change.newContent,
          original.sha,
          `fix: ${error.title}`,
        )
      }

      const pr = await this.github.createPullRequest(
        branchName,
        `fix: ${error.title}`,
        this.buildPRBody(error.title, error.message, fix.rootCause, fix.explanation, fix.confidence, error.sourceUrl),
      )

      const result: EngineResult = { success: true, pr }

      // 7. 알림 (best-effort)
      if (this.notification) {
        try {
          await this.notification.notify(result, error)
        } catch {
          // 알림 실패는 엔진을 멈추지 않음
        }
      }

      return result

    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      return { success: false, error: message }
    }
  }

  private buildPRBody(
    title: string,
    message: string,
    rootCause: string,
    explanation: string,
    confidence: string,
    sourceUrl?: string,
  ): string {
    const parts: string[] = []

    parts.push('## 🔍 Error')
    parts.push(`**${title}**`)
    parts.push(`${message}`)
    if (sourceUrl) {
      parts.push(`[View in Sentry](${sourceUrl})`)
    }

    parts.push('')
    parts.push('## 🧠 Root Cause')
    parts.push(rootCause)

    parts.push('')
    parts.push('## 🔧 Fix')
    parts.push(explanation)

    parts.push('')
    parts.push(`**Confidence:** ${confidence}`)

    parts.push('')
    parts.push('---')
    parts.push('*Generated by [Kintsugi Ops Engine](https://github.com/kintsugi-ops/engine)*')

    return parts.join('\n')
  }
}
